### ISSUE TITLE
specificity.keegan.st website down

### ISSUE THREAD

**Issue by tanmayrajani** [keeganstreet/specificity.keegan.st#3]
The webapp doesn't seem to be reachable at the moment. Is it known/intentional? 

Also, thanks much for making this. Very very useful :)

**Comment by keeganstreet** [comment]
Sorry, not intentional! I have restarted it. Thanks for letting me know.

**Comment by tanmayrajani** [comment]
Thanks for the quick resolution, it's up and running. Closing. :clinking_glasses:
