### ISSUE TITLE
License for commercial use?

### ISSUE THREAD

**Issue by nielsbom** [keeganstreet/specificity.keegan.st#6]
Hi!

I'd love to reuse this for Winc Academy (a bootcamp-like school). But I see no license for this project, I do see one for the calculator itself.

Are you OK with other people/orgs hosting a version of this somewhere else?

Thanks!

**Comment by keeganstreet** [comment]
Hey Niels, Yes that's fine with me.

**Comment by nielsbom** [comment]
Thank you!
