### ISSUE TITLE
Error in Sorting 

### ISSUE THREAD

**Issue by twittwer** [keeganstreet/specificity.keegan.st#8]
As soon as the selectors are changed from their initial value the `result` property of the items changes from the specificity object to item's change event. That's why `result.total` is undefined and the sort function throws with `Cannot read properties of undefined (reading 'A')`

https://github.com/keeganstreet/specificity.keegan.st/blob/e725020a60d9a27ceed9270b0b9c14b7436a432d/src/app/app.js#L38-L40

I tried to fix the problem, but as I never worked with vue before I didn't get what's going on at first glance.

> PS: The specificity calaculator is always a nice tool to quickly check on CSS issues 👍

**Comment by keeganstreet** [comment]
Hey @twittwer , thanks for catching this bug. It was introduced when I added support for level 4 selectors a few weeks ago. Pushing up a fix shortly.

> I tried to fix the problem, but as I never worked with vue before I didn't get what's going on at first glance.

No probs! I don't really get what's going on in this Vue app either 😅 It looks like the app component is mutating its state in the sort function. Could definitely do with a cleanup.

Glad you like the tool 👍
